# Generated by Django 5.1.7 on 2025-04-23 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobtitle', models.CharField(max_length=100)),
                ('compname', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('compdesc', models.TextField()),
                ('complocation', models.CharField(max_length=100)),
            ],
        ),
    ]
