# Generated by Django 5.2 on 2025-05-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='complocation',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='compname',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='jobtitle',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(max_length=200),
        ),
    ]
